[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.68.3"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
  HUGO_BUILDFUTURE = "true"

[context.branch-deploy.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
  HUGO_BUILDFUTURE = "true"
