# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
[[main]]
    name = "News"
    url = "/news/"
    weight = 2
[[main]]
    name = "Learn"
    url = "/learn/"
    weight = 3
[[main]]
    name = "Help"
    url = "/help/"
    weight = 4
[[main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 5
