---
title: Intermediates
subtitle: Expand your skills
abstract: Expand your R skills.
description: >
    Here are some common areas that people who already have some experience in R find particularly rewarding to learn.
weight: 2
bibliography: [../books.bib, packages.bib] 
link-citations: true
nocite: | 
  @R-reprex, @R-ggplot2, @R-shiny, @R-flexdashboard, @R-tidymodels, @R-parsnip, @R-sparklyr, @R-quantmod
---

```{r include=FALSE}
knitr::write_bib(c("reprex", "ggplot2", "shiny", "flexdashboard", "tidymodels", "parsnip", "sparklyr", "quantmod"), "packages.bib") 
```

Once you've gotten started learning R, you can expand your skills by exploring many of the specialized capabilities of R. Here are 6 of the most common areas that people who already have some experience in R find particularly rewarding to learn.

- __Grab some cheat sheets.__ No one can possibly remember all the functions and arguments for every R package, which is why cheat sheets were invented. RStudio publishes a [free collection of cheat sheets](https://www.rstudio.com/resources/cheatsheets/) for the most popular R features and packages to help jog your memory. If you decide you'd like to collect them all, you may clone [the cheat sheet github repository](https://www.rstudio.com/resources/cheatsheets/). 

- __Learn to get help.__ Everyone gets stuck. Learning where and how to ask for R help is a powerful skill to hone. The Tidyverse site offers some expert advice for [how to help others help you](https://www.tidyverse.org/help/). One package you'll grow to love is the [reprex package](https://reprex.tidyverse.org) for creating reproducible R code examples. Read through the [reprex](https://reprex.tidyverse.org) articles, which feature loads of animated gifs to illustrate the steps like [_Magic reprex_](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) and [_Using datapasta with reprex_](https://reprex.tidyverse.org/articles/articles/datapasta-reprex.html). Where to ask for help? The [RStudio Community](https://community.rstudio.com/) is a warm and welcoming online discussion forum to ask (and answer!) any questions about using R.

- __Improve your visualizations.__ You may already know how to create a basic plot using ggplot2, but can you build one that makes your audience go "Wow?" You can start by expanding your knowledge of the Grammar of Graphics and ggplot2 by reading Hadley Wickham's [-@wickham2016ggplot2] book, *ggplot2: Elegant Graphics for Data Analysis*. Paper and Kindle versions are [available on Amazon](https://www.amazon.com/ggplot2-Elegant-Graphics-Data-Analysis-ebook/dp/B01GVCRF6M) for the second edition of the book. The third edition is in-progress and can be viewed for [free online](https://ggplot2-book.org/), with the source files on [GitHub](https://github.com/hadley/ggplot2-book). If you'd like Hadley to personally explain his philosophy of using ggplot2 in his data science work, check out Hadley's talk from OpenVisConf 2017, [ *The Role of Visualiation in Exploratory Data Analysis*](https://youtu.be/ZdPNBF6GWBw). Bookmark the updated [*R Graphics Cookbook*](https://r-graphics.org/) by Winston Chang [-@chang2018r] too; it is filled with recipes that tackle specific ggplot2 problems.

- __Develop interactive applications with htmlwidgets and Shiny.__ One concrete way to communicate your analyses better is to make your visualizations interactive. You can learn how to add browser-based interactivity to your graphics with just a few lines of code at [www.htmlwidgets.org](https://www.htmlwidgets.org). If your interactive needs demand help from R code that needs to run on a server, learn how to write Shiny applications at [shiny.rstudio.com](https://shiny.rstudio.com), or follow along as @wickham2020shiny writes the new [Mastering Shiny](https://mastering-shiny.org/) book. Both approaches can be integrated with R Markdown to create polished interactive dashboards using the [flexdashboard package](https://rmarkdown.rstudio.com/flexdashboard/).

-	__Simplify your model explorations with *tidymodels*.__ Much of data science involves modeling, but each modeling package seems to invent its own interface and arguments. Enter [tidymodels](https://github.com/tidymodels), a meta-package for modeling and analysis that shares the underlying design philosophy, grammar, and data structures of the tidyverse. If you previously have used caret for a uniform modeling interface, the [tidymodels package parsnip](https://tidymodels.github.io/parsnip/) is its more up-to-date child. While this project is still under development, it promises to dramatically simplify model exploration. RStudio's [Edgar Ruiz](https://twitter.com/theotheredgar) wrote up [_A Gentle Introduction to tidymodels_](https://rviews.rstudio.com/2019/06/19/a-gentle-intro-to-tidymodels/) to get you started.

- __Explore other specialized packages.__ R attracts data scientists because of its more than 13,000 packages that address nearly every use case. If you're interested in genomics, you'll want to spend some time learning the [*bioconductor* collection of packages](https://bioconductor.org/). If you're working with Big Data on Spark clusters, check out [sparklyr](https://sparklyr.rstudio.com). If you want to dive into finance, you'll probably want to start with [quantmod](http://www.quantmod.com). To find out what packages you should explore, we recommend some of the topic-based package catalogs such as [Awesome R](https://awesome-r.com/) or the [CRAN task views](https://cran.r-project.org/web/views/).

\

<details><summary>Books & packages referenced</summary>
<p>
