---
title: Experts
subtitle: Go deep
abstract: Go deep.
description: >
    Learning some topics in depth will both help you develop better code and share it more effectively with others.
weight: 3
bibliography: [../books.bib, packages.bib] 
link-citations: true
nocite: | 
  @R-tensorflow, @R-reticulate, @R-pkgdown, @R-bookdown, @R-distill, @R-blogdown, @R-xaringan
---

```{r include=FALSE}
knitr::write_bib(c("tensorflow", "reticulate", "pkgdown", "bookdown", "distill", "blogdown", "xaringan"), "packages.bib") 
```


Even once you are an expert at R code development, learning some topics in depth will both help you develop better code and share it more effectively with others.

- __Dive into the foundations of R.__ Most R users are not programmers, and therefore much of their R code is not as readable, fast, or efficient as it could be. The second edition of Hadley Wickham's book, *Advanced R* [-@wickham2019advanced] (available for [free online](https://adv-r.hadley.nz/) and as [an O'Reilly paperback from Amazon](https://www.amazon.com/dp/0815384572/ref=cm_sw_r_tw_dp_U_x_aJ-IDb98S6FE7)), unlocks many of the secrets behind how R works the way it does, and gives you new strategies for solving diverse problems. You may also want to bookmark [_Advanced R Solutions_](https://advanced-r-solutions.rbind.io/), which provides worked solutions to the exercises in this book.

- __Learn how to extend R.__ While its content sometime overlaps with Hadley's *Advanced R*, the R Core Team offers *Writing R Extensions* ([electronic version](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)) on CRAN. This book is particularly useful if you wish to add your own C and C++ routines to R, but also has unique information on debugging, the R API, and runtime profiling that is difficult to find anywhere else.

- __Build your own packages.__ R packages allow you to share your functions with other R programmers in a modular and easy-to-integrate way. The above-mentioned *Writing R Extensions* documents how to write packages, but you may find Hadley Wickham's *R Packages* book [-@wickham2015r] ([electronic here (1st edition)](http://r-pkgs.had.co.nz/) and [an O'Reilly paperback (1st edition) from Amazon here](https://www.amazon.com/dp/1491910593/ref=cm_sw_su_dp?tag=r-pkgs-20)) a bit easier to read and more step-by-step. The second edition of the *R Packages* book is currently in progress, written by Hadley and co-author Jenny Bryan. You can read the in-progress book for [free online](https://r-pkgs.org/). If you want your R code to reach the widest possible population of developers, you'll want to know how to build packages. 

- __Use Python in your analyses.__ Anyone who insists you must choose between R and Python for doing data science is creating a false choice. R offers an easy way to incorporate Python code in the [reticulate package](https://rstudio.github.io/reticulate). Sean Lopp's webinar, [*R, RStudio 1.2 & Python—a love story*](https://resources.rstudio.com/webinars/r-rstudio-1-2-amp-python-a-love-story-sean-lopp), demonstrates how easily developers can integrate Python code into their R workflows and walks through the development of a reticulated Shiny app.

- __Try your hand at Tensorflow for deep learning.__ RStudio hosts a web site dedicated to R and Tensorflow at [tensorflow.rstudio.com](https://tensorflow.rstudio.com), where you can learn how to use deep learning in your analyses. 
J.J. Allaire and Francois Chollet have published a [*Deep Learning with R* book](https://www.amazon.com/Deep-Learning-R-Francois-Chollet/dp/161729554X) [-@chollet2018deep]. You can hear J.J. describe the philosophy behind the system in his [rstudio::conf 2019 video](https://www.rstudio.com/resources/videos/machine-learning-with-tensorflow-and-r/). For an quick overview of  resources for how to get started with deep learning in R, read [Sigrid Keydana's article](https://blog.rstudio.com/2018/09/12/getting-started-with-deep-learning-in-r/) and subscribe to the [Tensorflow for R blog](https://blogs.rstudio.com/tensorflow/).

- __Communicate with R Markdown.__ The R Markdown family of packages enables you to create and share beautiful data science products like books, blogs, websites, and presentations. Experiment with packages like [bookdown](https://bookdown.org/yihui/bookdown/), [distill](https://rstudio.github.io/distill/), and [blogdown](https://bookdown.org/yihui/blogdown/); each extends R Markdown to help you publish polished websites for sharing your work. If you want to present analyses or visualizations made with R code, consider making your slides with R Markdown using the [xaringan package](https://bookdown.org/yihui/rmarkdown/xaringan.html). If you've built an R package, the [pkgdown](https://pkgdown.r-lib.org/) package makes it quick and relatively painless to build a website for your package, using all the work you've already done to write and document your functions.

\

<details><summary>Books & packages referenced</summary>
<p>
