---
title: Beginners
subtitle: Get started
abstract: Get started with the Tidyverse and R Markdown.
description: >
    No one starting point will serve all beginners, but here are 6 ways to begin learning R.
weight: 1
bibliography: [../books.bib, packages.bib] 
link-citations: true
nocite: | 
  @R-ggplot2, @R-rmarkdown, @R-tidyverse
---

```{r include=FALSE}
knitr::write_bib(c("tidyverse", "ggplot2", "rmarkdown"), "packages.bib") 
```


No one starting point will serve all beginners, but here are 6 ways to begin learning R.

- __Install [<i class="fab fa-r-project"></i>](https://cloud.r-project.org/), [RStudio](http://www.rstudio.com/download), and R packages like the [tidyverse](https://www.tidyverse.org/).__ These three installation steps are often confusing to first-time users. For beginner-friendly installation instructions, we recommend the free online ModernDive chapter [_Getting Started with R and RStudio_](https://moderndive.netlify.com/1-getting-started.html). You may also enjoy the [_Basic Basics_](https://rladiessydney.org/courses/ryouwithme/basicbasics) lesson unit from [R-Ladies Sydney](https://rladiessydney.org), which provides an [opinionated tour of RStudio](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-1/) for new users and a [step-by-step guide to installing and using R packages](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-2/).

- __Spend an hour with [*A Gentle Introduction to Tidy Statistics In R*](https://resources.rstudio.com/webinars/a-gentle-introduction-to-tidy-statistics-in-r).__ If you are coming to R from a traditional point-and-click statistics package such as SPSS or SAS, RStudio's [Thomas Mock](https://twitter.com/thomas_mock) has created a free video webinar titled [A Gentle Introduction to Tidy Statistics In R](https://resources.rstudio.com/webinars/a-gentle-introduction-to-tidy-statistics-in-r). This one-hour introduction covers how to get started quickly with the basics of research statistics in R, providing an emphasis on reading data into R, exploratory data analysis with the tidyverse, statistical testing with ANOVAs, and finally producing a publication-ready plot in ggplot2. Plus, you'll find a host of other RStudio webinars and videos to explore via the topic menus on the left side of that page.

- __Read [*R for Data Science*](https://r4ds.had.co.nz).__ While videos are great for some, others of us learn best by curling up with a good book. If that describes you, pick up a copy of *R For Data Science* by @wickham2016r from your friendly local bookseller. *R For Data Science* is available in [paper](https://www.amazon.com/Data-Science-Transform-Visualize-Model-dp-1491910399/dp/1491910399/ref=mt_paperback?_encoding=UTF8&me=&qid=1562083100) and [electronic](https://www.amazon.com/Data-Science-Transform-Visualize-Model-ebook-dp-B01NAJAEN5/dp/B01NAJAEN5/ref=mt_kindle?_encoding=UTF8&me=&qid=1562083100) forms and has been translated into multiple languages including [Spanish](https://es.r4ds.hadley.nz/), so choose the version that's easiest for you. **_R For Data Science_ is also available for free as a online book at [https://r4ds.had.co.nz](https://r4ds.had.co.nz).** If you don't yet know enough about R to commit to *R for Data Science*, you may find Garrett Grolemund's [*Hands On Programming with R*](https://rstudio-education.github.io/hopr/) [-@grolemund2014hands] a quicker way to get started. It's also available in [paper](https://www.amazon.com/Hands-Programming-Write-Functions-Simulations/dp/1449359019), [electronic](https://www.amazon.com/Hands-Programming-Write-Functions-Simulations-ebook-dp-B00LPUIB8C/dp/B00LPUIB8C/ref=mt_kindle?_encoding=UTF8&me=&qid=), and [free online versions](https://rstudio-education.github.io/hopr/).

- __Start coding using [RStudio.cloud Primers](https://rstudio.cloud/learn/primers).__ One of the most effective ways to get started learning R is to start using it. [RStudio.cloud Primers](https://rstudio.cloud/learn/primers) offer a cloud-based learning environment that will teach you the basics of R all from the comfort of your browser. RStudio.cloud doesn't require you to install any software on your computer, making it easy to dip your toe into data science with R with a minimum of fuss. And best of all, rstudio.cloud accounts are free for personal use.

- __Publish your work with R Markdown.__ R is a terrific tool for telling stories with graphics and data, but sometimes you need words too. R Markdown weaves together narrative text and code to produce elegantly formatted reports, papers, books, slides and more. Garrett Grolemund will give you a personal R Markdown tour with his [*Get Started With R Markdown*](https://resources.rstudio.com/the-essentials-of-data-science/getting-started-with-r-markdown-60-02) video, or you can choose your own path through the wonders of R Markdown at [rmarkdown.rstudio.com](https://rmarkdown.rstudio.com). Bookmark [*R Markdown: The Definitive Guide*](https://bookdown.org/yihui/rmarkdown/) [-@xie2018r] as you work too; it provides a great overview of what is possible within the R Markdown family of packages.

- __Learn about some power tools for development.__ RStudio offers 6 videos called the [RStudio Essentials Series](https://resources.rstudio.com) that help you learn how to program and manage R projects using RStudio's tools including the RStudio Integrated Development Environment (IDE). These videos will also help you learn good development practices that make collaboration within a team safe and easy.

\


<details><summary>Books & packages referenced</summary>
<p>


