name = "tourmaline"
license = "MIT"
licenselink = "https://github.com/rstudio/hugo-tourmaline/blob/master/LICENSE.md"
description = "A simple responsive blog theme for Hugo forked from versions by Jonathan Rutheiser and Yihui Xie, with modifications to make it work better for teams."
homepage = ""
min_version = "0.53"
tags = ["teams",
        "responsive",
        "blog",
        "minimal"
        ]
features = ["blog",
            "events",
            "authors"
            ]

[author]
  name = "Alison Hill"
  homepage = "https://alison.rbind.io/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""